server:
  port: 8763
  #port : 876555
  
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Akey1970/microservices-tutorial-config
          clone-on-start: true
            
